version: '3'

tasks:
  push:
    cmds:
      - git pull
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push

  prepare:
    cmds:
      - cargo fmt
      - cargo clippy
      - cargo audit
      - cargo test
      - cargo tarpaulin --ignore-tests

  run:
    cmds:
      - cargo run -p tutor-nodb
